name: Build

on:
  push:
    branches:
      - main
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Install neutralino
        run: npm install -g @neutralinojs/neu

      - name: Build
        run: neu build --release

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: neutralino-build
            path: dist
